In [1]:
import numpy as np

data1 = np.array([1,2,3])
data1.shape

(3,)

In [2]:
data3 = np.array([
    [1.,2.,3.], [4.,5.,6.]
])
data3.shape

(2, 3)

In [3]:
data3.ndim

2

In [4]:
data = np.arange(6).reshape(1,2,3)
print(data, data.shape)

[[[0 1 2]
  [3 4 5]]] (1, 2, 3)


In [5]:
np.zeros(shape=(2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
data1 = np.array([ [1, 2], [3, 4], [5, 6] ])
data2 = np.array([ [1], [2], [3] ])
print (data1 + data2, '\n')

data3 = np.array([ [1, 2, 3] ])
print ("data3", data3, data3.shape, '\n')
print (data2 + data3, '\n')

[[2 3]
 [5 6]
 [8 9]] 

data3 [[1 2 3]] (1, 3) 

[[2 3 4]
 [3 4 5]
 [4 5 6]] 

