In [8]:
import torch

x= torch.rand(1, requires_grad=True)
y = torch.rand(1)
y.requires_grad = True
loss = y-x

In [9]:
loss.backward()
print(x.grad, y.grad)

tensor([-1.]) tensor([1.])


In [10]:
x=torch.ones(4)
y = torch.zeros(3)
W = torch.rand(4,3, requires_grad=True)
b=torch.rand(3,requires_grad=True)
z=torch.matmul(x,W)+b
print(W,b,z)

tensor([[0.0569, 0.8867, 0.5724],
        [0.6367, 0.4474, 0.7930],
        [0.0605, 0.4417, 0.9671],
        [0.5428, 0.0057, 0.2992]], requires_grad=True) tensor([0.7784, 0.0515, 0.8422], requires_grad=True) tensor([2.0753, 1.8331, 3.4739], grad_fn=<AddBackward0>)


In [11]:
import torch.nn.functional as f
loss = f.mse_loss(z,y)
loss.backward()
print(W.grad, b.grad)

tensor([[1.3835, 1.2220, 2.3159],
        [1.3835, 1.2220, 2.3159],
        [1.3835, 1.2220, 2.3159],
        [1.3835, 1.2220, 2.3159]]) tensor([1.3835, 1.2220, 2.3159])


In [12]:
import torch
w = torch.tensor(4.0, requires_grad=True)
z=2*w
z.backward() #이러면 w.grad에  2가 저장이되나?
print(w.grad) # w->A ->z 로 식이가면 w.grad에는 z의 w편미분이 들어간다

tensor(2.)


In [13]:
import torch
import torch.nn.functional as F
lr = 0.01
optimizer = torch.optim.SGD([W,b], lr=lr)
for i in range(300):
    z= torch.matmul(x,W)+b
    loss = F.mse_loss(z,y)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if i%100==0:
        print(i,W,b,loss)

0 tensor([[ 0.0431,  0.8745,  0.5493],
        [ 0.6229,  0.4352,  0.7698],
        [ 0.0466,  0.4295,  0.9439],
        [ 0.5290, -0.0065,  0.2760]], requires_grad=True) tensor([0.7646, 0.0393, 0.8191], requires_grad=True) tensor(6.5783, grad_fn=<MseLossBackward0>)
100 tensor([[-0.3446,  0.5321, -0.0997],
        [ 0.2352,  0.0928,  0.1208],
        [-0.3411,  0.0870,  0.2950],
        [ 0.1413, -0.3490, -0.3730]], requires_grad=True) tensor([ 0.3769, -0.3032,  0.1701], requires_grad=True) tensor(0.0075, grad_fn=<MseLossBackward0>)
200 tensor([[-0.3577,  0.5205, -0.1216],
        [ 0.2221,  0.0812,  0.0989],
        [-0.3541,  0.0755,  0.2731],
        [ 0.1282, -0.3605, -0.3949]], requires_grad=True) tensor([ 0.3638, -0.3147,  0.1482], requires_grad=True) tensor(8.4879e-06, grad_fn=<MseLossBackward0>)


In [15]:
import torch.nn as nn
class LinearRegression(nn.Module):
    def __init__(self, input_dim, output_dim):
        super().__init__()
        self.linear = nn.Linear(input_dim, output_dim)

    def forward(self,x):
        return self.linear(x)

model = LinearRegression(4,3)

In [16]:
x = torch.ones(4)  # input tensor
y = torch.zeros(3)  # expected output

learning_rate = 0.01
nb_epochs = 1000
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)  #w랑 b가 모델 파라미터에잇음

for epoch in range(nb_epochs + 1):

    pred = model(x)
    loss = F.mse_loss(pred, y)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

In [19]:
print(loss)
for param in model.parameters():
    print (param)

tensor(1.3130e-13, grad_fn=<MseLossBackward0>)
Parameter containing:
tensor([[ 0.1290, -0.1585, -0.0169, -0.0455],
        [-0.1461,  0.0824, -0.1381,  0.1239],
        [ 0.0386,  0.1285, -0.1844,  0.3003]], requires_grad=True)
Parameter containing:
tensor([ 0.0918,  0.0779, -0.2830], requires_grad=True)


In [18]:
print(model.parameters())

<generator object Module.parameters at 0x0000022E46063E60>
