In [1]:
import numpy as np
from torch.fx.experimental.migrate_gradual_types.z3_types import dyn_type

data1 = np.array(10)
print(data1, data1.ndim, data1.shape)

10 0 ()


In [2]:
import torch
data1 = torch.FloatTensor([1,2])
print(data1, data1.dim(), data1.shape, data1.size())

data2  =torch.FloatTensor(3)
print(data2, data2.dim(), data2.shape, data2.size())

tensor([1., 2.]) 1 torch.Size([2]) torch.Size([2])
tensor([0., 0., 0.]) 1 torch.Size([3]) torch.Size([3])


In [3]:
data3 = torch.FloatTensor(3,2)
print(data3, data3.dim(), data3.shape)

data4 = torch.FloatTensor([
    [1,2], [3,4], [5,6]
])
print(data4, data4.dim(), data4.shape)

tensor([[-2.3420e+18,  1.5036e-42],
        [ 0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00]]) 2 torch.Size([3, 2])
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]]) 2 torch.Size([3, 2])


In [5]:
data5 = torch.FloatTensor(3,2,1)
for one in data5:
    print(one)

tensor([[0.],
        [0.]])
tensor([[0.],
        [0.]])
tensor([[0.],
        [0.]])


In [6]:
data6 = torch.FloatTensor([
    [[1],[2]], [[3], [4]], [[5],[6]]
])
data6.shape

torch.Size([3, 2, 1])

In [7]:
d7 = torch.FloatTensor([
    [1],[2],[3]
])
d7.shape

torch.Size([3, 1])

In [8]:

d8 = torch.FloatTensor([
    [1,2,3]
])
d8.shape

torch.Size([1, 3])

In [9]:
data1 = torch.DoubleTensor([
    [1,2,3], [4,5,6]
])
data1.reshape(3,2)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]], dtype=torch.float64)

In [10]:
data1.reshape(2,-1)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

In [12]:
data1 = torch.FloatTensor([
    [1],[2], [3]
])
print(data1)
print(data1.squeeze())


tensor([[1.],
        [2.],
        [3.]])
tensor([1., 2., 3.])


In [14]:
print(data1.unsqueeze(0).shape)

torch.Size([1, 3, 1])


In [16]:
print(data1.unsqueeze(1).shape)

torch.Size([3, 1, 1])


In [17]:
print(data1.unsqueeze(1))

tensor([[[1.]],

        [[2.]],

        [[3.]]])


In [18]:
data1 = torch.zeros(2, dtype=torch.float)
data2 = torch.ones(2,4, dtype = torch.double)
data3 = torch.rand(2,2,3, dtype=torch.half)
print(data1.dtype, data2.dtype, data3.dtype)

torch.float32 torch.float64 torch.float16
