In [2]:
import torch
A = torch.full((3,), 2) #3차 벡터
B = torch.full((3,), 3)
print(A, A.dim(), A.shape)
print(B, B.dim(), B.shape)

result = torch.matmul(A,B)
print(result, result.shape)

tensor([2, 2, 2]) 1 torch.Size([3])
tensor([3, 3, 3]) 1 torch.Size([3])
tensor(18) torch.Size([])


In [3]:
A = torch.full((3,2),2)
B = torch.full((2,3),3)
result = torch.matmul(A,B)
print(result.shape)

torch.Size([3, 3])


In [4]:
X = torch.full((3,),2)
A = torch.full((3,2),3)
result = torch.matmul(X,A)
print(result,  result.shape)

tensor([18, 18]) torch.Size([2])


In [6]:
X = torch.full((3,),2)
A = torch.full((4,3,2),3)
result = torch.matmul(X,A)
print(result,  result.shape)


tensor([[18, 18],
        [18, 18],
        [18, 18],
        [18, 18]]) torch.Size([4, 2])


In [7]:
data1 = torch.full((10,8,3,4),2)
data2 = torch.full((1,8,4,5),3)
data3 = torch.matmul(data1,data2)
data3.shape

torch.Size([10, 8, 3, 5])

In [8]:
data1 = torch.full((10, 8, 3, 4), 2) # matrix 생성
data2 = torch.full((1, 8, 4, 5), 3) # vector 생성


data3 = torch.matmul(data1, data2) # 10 x ((3, 4) x (4, 5))
print (data3.shape) # 10 x (3, 5) = (10, 3, 5)

torch.Size([10, 8, 3, 5])
