In [2]:
import torch

x = torch.rand(4)
W = torch.rand(4,3)
b = torch.rand(3)

def linearfunction(x,W,b):
    y = torch.matmul(x,W)+b
    return y
print('W', W.shape, 'X', x.shape, 'B',b.shape)

W torch.Size([4, 3]) X torch.Size([4]) B torch.Size([3])


In [3]:
y = linearfunction(x,W,b)
y.shape

torch.Size([3])

In [4]:
import torch
import torch.nn as nn

class NeuralNetwork(nn.Module):
    def __init__(self):

        super().__init__()

        self.W = torch.FloatTensor(4,3)
        self.b = torch.FloatTensor(3)

    def forward(self,x):
        y = torch.matmul(x,self.W)+self.b
        return y



In [5]:
x = torch.rand(4)
mylinear = NeuralNetwork()
y = mylinear(x)
print(y)

tensor([8.9044e+10, 1.2009e-42, 0.0000e+00])


In [6]:
import torch
import torch.nn as nn

class NeuralNetwork(nn.Module):
    def __init__(self,input_size, output_size):

        super().__init__()

        self.W = torch.rand(input_size,output_size)
        self.b = torch.rand(output_size)


    def forward(self,x):
        return torch.matmul(x,self.W) +self.b

In [7]:
x= torch.rand(4)
myLinear = NeuralNetwork(4,3)
y = myLinear(x)
print(y, y.shape)

tensor([0.7505, 0.9673, 1.2688]) torch.Size([3])


In [8]:
class sibal(nn.Module):
    def __init__(self, i,o):
        super().__init__()

        self.W = nn.Parameter(torch.rand(i, o))
        self.b = nn.Parameter(torch.rand(o))

    def forward(self,x):
        return torch.matmul(x,self.W)+self.b

In [9]:
x= torch.FloatTensor([100,1000,2,3])
obj = sibal(4,100)
res = obj(x)
print(res,res.shape)

tensor([ 245.9961,  793.2139,  416.1255,  882.1088,  200.6880,  541.9631,
         767.1176,  703.3215,  811.9828,  693.5402,  739.4570,  507.0086,
         203.1945,   95.7775,  589.9572, 1005.0896,  906.1785,  661.9045,
         676.6324,  699.2148,  130.4627,  441.7180,  228.3384,  279.2445,
         549.0126,  172.2645,  653.5194,   93.0877,  668.1766,  307.4227,
         128.3017,  264.7738,  876.9245,  398.3674,  277.6920,  157.6969,
         118.9015,  731.7160, 1016.8666,   59.7378,  678.0278,  789.7137,
          60.1745,   13.1310,  549.4503,  187.7483,  573.3090,  507.6866,
         692.9382,  783.9695,  463.1754,  707.6605,  208.6580,  945.9653,
         855.3081,  465.9852,  954.1973,  135.9174,  507.8174,  143.0280,
         572.7159,  429.0280,  590.2283,  195.9892,  167.4037,   73.2635,
         331.9398,  826.9182,  335.5622,  535.0338,  531.7628,  278.3536,
         847.3575,   42.2859,  997.3226,  135.3166,  740.0367,  258.8784,
         237.7234,  495.3869,  946.301

In [10]:
x = torch.rand(5)
obj = nn.Linear(5,3)
res = obj(x)
print(res, res.shape)

tensor([0.3242, 0.1080, 0.0872], grad_fn=<ViewBackward0>) torch.Size([3])


In [1]:
import torch.nn as nn
import  torch
#nn.Linear(a,b) 하면 가중치 입력 a개 출력 b개에 맞춘 가중치 (a,b) 행렬과 입력 b차원 벡터가 있는 선형 함수가 만들어지는것
class last(nn.Module):
    def __init__(self, i, o): ##nn 에는 선형함수를 정의해놓은 필드가잇음
        super().__init__()
        self.linear = nn.Linear(i,o)  #self. linear은 nn에 선형함수가 잇나보지 그게 linear라는 변수고 선형함수를 정의해놓는 필드인듯

    def forward(self,x):
        y = self.linear(x)
        return y


mylinear = last(4, 3)
x= torch.rand(4)
y = mylinear(x)
print (y, y.shape)

tensor([0.4910, 0.1932, 0.3384], grad_fn=<ViewBackward0>) torch.Size([3])
