In [1]:
from textwrap import indent

import torch
import torch.nn as nn




class LinearRegressionModel(nn.Module):
    def __init__(self,i,o):
        super().__init__()
        self.linear = nn.Linear(in_features=i,out_features=o)
        self.activation = nn.Sigmoid()

    def forward(self,x):
        return self.activation(self.linear(x))

In [2]:
import torch.nn.functional as F
x= torch.ones(4)
y = torch.zeros(3)
model = LinearRegressionModel(4,3)

loss_function = nn.MSELoss()

In [3]:
learning_rate = 0.01
nb_epochs = 1000
optimizer = torch.optim.SGD(model.parameters(), lr = learning_rate)

for epoch in range(1001):
    y_pred = model(x)
    loss = loss_function(y_pred,y)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

In [4]:
print(loss)
for param in model.parameters():
    print(param)

tensor(0.0236, grad_fn=<MseLossBackward0>)
Parameter containing:
tensor([[-0.3500, -0.0587, -0.6135, -0.6660],
        [-0.1161, -0.7080,  0.0258, -0.1687],
        [-0.0401, -0.5380, -0.2650, -0.4999]], requires_grad=True)
Parameter containing:
tensor([-0.0020, -0.7361, -0.3893], requires_grad=True)


In [5]:
import torch
import torch.nn as nn

class LinearRegressionModel(nn.Module):
    def __init__(self,i,o):
        super().__init__()
        self.linear1= nn.Linear(i,10)
        self.linear2 = nn.Linear(10,10)
        self.linear3 = nn.Linear(10,10)
        self.linear4 = nn.Linear(10,o)
        self.sibal = nn.LeakyReLU(0.1)

    def forward(self,x):
        hidden =self.sibal(self.linear1(x))
        hidden =self.sibal(self.linear2(hidden))
        hidden =self.sibal(self.linear3(hidden))
        y = self.linear4(hidden)
        return y

In [6]:
x = torch.ones(4)
y = torch.zeros(3)
model = LinearRegressionModel(4,3)
loss_function = nn.MSELoss()

In [7]:
learning_rate = 0.01
nb_epochs=1000
optimizer = torch.optim.SGD(model.parameters(), lr = learning_rate)

for epoch in range(nb_epochs+1):
    y_pred = model(x)
    loss = loss_function(y_pred, y)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

In [8]:
print(loss)
for param in model.parameters():
    print(param)

tensor(3.4560e-11, grad_fn=<MseLossBackward0>)
Parameter containing:
tensor([[-0.4039, -0.3337,  0.4503,  0.2896],
        [ 0.2244, -0.4961,  0.0430, -0.0961],
        [ 0.3162,  0.0765,  0.4228,  0.4019],
        [ 0.2477,  0.0848, -0.1197, -0.2077],
        [-0.1258, -0.4975, -0.3375,  0.3980],
        [-0.1365,  0.4554,  0.1481, -0.2519],
        [-0.3008, -0.1155, -0.1635, -0.0847],
        [-0.1449, -0.2383, -0.0770,  0.3985],
        [ 0.3125, -0.4263, -0.4459,  0.3084],
        [ 0.3270, -0.4502, -0.4048, -0.0791]], requires_grad=True)
Parameter containing:
tensor([ 0.1965, -0.4276,  0.0334,  0.0446,  0.3557,  0.0310,  0.0490,  0.2273,
        -0.0297,  0.4061], requires_grad=True)
Parameter containing:
tensor([[ 0.0711, -0.1848, -0.2612, -0.0149, -0.1862, -0.1852, -0.0103, -0.2899,
          0.1769,  0.2216],
        [ 0.0732, -0.1346,  0.0785,  0.0603,  0.0395, -0.0140, -0.0407,  0.1881,
          0.0848,  0.0080],
        [-0.3157, -0.2374, -0.1773, -0.0690,  0.1486,  0.0186

In [9]:
model.linear1.weight

Parameter containing:
tensor([[-0.4039, -0.3337,  0.4503,  0.2896],
        [ 0.2244, -0.4961,  0.0430, -0.0961],
        [ 0.3162,  0.0765,  0.4228,  0.4019],
        [ 0.2477,  0.0848, -0.1197, -0.2077],
        [-0.1258, -0.4975, -0.3375,  0.3980],
        [-0.1365,  0.4554,  0.1481, -0.2519],
        [-0.3008, -0.1155, -0.1635, -0.0847],
        [-0.1449, -0.2383, -0.0770,  0.3985],
        [ 0.3125, -0.4263, -0.4459,  0.3084],
        [ 0.3270, -0.4502, -0.4048, -0.0791]], requires_grad=True)

In [10]:
x = torch.ones(4)
y = torch.zeros(3)

id = x.size(0)
od = y.size(0)

model = nn.Sequential(
    nn.Linear(id,10),
    nn.LeakyReLU(0.1),
    nn.Linear(10,10),
    nn.LeakyReLU(0.1),
    nn.Linear(10,10),
    nn.LeakyReLU(0.1),
    nn.Linear(10,od)
)

In [11]:
loss_function = nn.MSELoss()
learning_rate=0.01
np_epochs = 1000
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

for epoch in range(np_epochs+1):
    y_pred = model(x)
    loss = loss_function(y_pred, y)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

print(loss)
for param in model.parameters():
    print(param)

tensor(8.0163e-10, grad_fn=<MseLossBackward0>)
Parameter containing:
tensor([[ 0.2734,  0.2509,  0.1609, -0.4728],
        [-0.4864, -0.1457,  0.2038,  0.2101],
        [-0.0899,  0.1436,  0.0122,  0.0545],
        [ 0.4998,  0.3512, -0.4660,  0.4928],
        [-0.3130,  0.1713, -0.2367,  0.3650],
        [-0.4886,  0.1143,  0.4641, -0.2659],
        [ 0.0416,  0.3038,  0.4675, -0.2384],
        [-0.0060,  0.2147,  0.1426, -0.0072],
        [-0.1185,  0.3159,  0.4625,  0.0785],
        [ 0.2839, -0.1750,  0.4704, -0.2900]], requires_grad=True)
Parameter containing:
tensor([-0.2127, -0.1117,  0.0287,  0.1697, -0.3354, -0.1874,  0.1696, -0.3909,
         0.3579, -0.0712], requires_grad=True)
Parameter containing:
tensor([[-2.5057e-01, -2.5532e-01, -2.4925e-01,  8.4913e-02, -3.0912e-01,
         -1.3153e-01, -1.0457e-01, -2.1950e-04, -1.0125e-01, -2.7729e-01],
        [-1.0693e-01,  1.0747e-01, -1.0253e-01,  2.1316e-01,  1.7446e-01,
         -7.8016e-02,  7.5239e-02,  1.2371e-01, -9.0768e

In [12]:
data1 = torch.randn(3, 4)
print (data1)
indices = torch.tensor([1, 2])
print (indices)
print (torch.index_select(data1, 0, indices))
print (torch.index_select(data1, 1, indices))

tensor([[-1.8559, -0.2937, -0.4256, -0.3871],
        [-0.8946, -0.8675,  0.9737,  1.0733],
        [-0.1774, -0.1469, -2.0674,  2.0635]])
tensor([1, 2])
tensor([[-0.8946, -0.8675,  0.9737,  1.0733],
        [-0.1774, -0.1469, -2.0674,  2.0635]])
tensor([[-0.2937, -0.4256],
        [-0.8675,  0.9737],
        [-0.1469, -2.0674]])


In [13]:
x = torch.ones(5000,10)
y = torch.zeros(5000,1)
learning_rate = 0.01
iter_num = 1000
minibatch_size = 256

In [14]:
input_dim = x.size(-1)
output_dim = y.size(-1)

# 보통 hidden layer 는 출력에 가까울 수록 작아지게 설계하는 것이 일반적임 (더 좋은 성능)
model = nn.Sequential (
    nn.Linear(input_dim, 10),
    nn.LeakyReLU(0.1),
    nn.Linear(10, 8),
    nn.LeakyReLU(0.1),
    nn.Linear(8, 6),
    nn.LeakyReLU(0.1),
    nn.Linear(6, output_dim)
)

loss_function = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

In [15]:
input_dim

10

In [16]:
indices = torch.randperm(x.size(0)) #(0 ~4999) 까지 섞은 배열을줌
print (indices)
x_batch_list = torch.index_select(x, 0, index=indices) # shuffle 된 데이터셋으로, 데이터양이 상당하므로, 미니배치 변수로 선언
y_batch_list = torch.index_select(y, 0, index=indices)

tensor([ 734,  198, 1625,  ..., 1827, 4169,  537])


In [17]:
indices

tensor([ 734,  198, 1625,  ..., 1827, 4169,  537])

In [18]:
x_batch_list = x_batch_list.split(minibatch_size, 0 )
y_batch_list = y_batch_list.split(minibatch_size, 0 )
print(len(x_batch_list), len(y_batch_list))

20 20


In [19]:
print(len(x_batch_list[19]))

136


In [20]:
for index in range(1000):
    indices = torch.randperm(x.size(0))

    x_batch_list = torch.index_select(x,0,index=indices)
    y_batch_list = torch.index_select(y,0,index=indices)
    x_batch_list = x_batch_list.split(minibatch_size,0)
    y_batch_list = y_batch_list.split(minibatch_size,0)

    for x, y in zip(x_batch_list, y_batch_list):
        y_pred = model(x)
        loss = loss_function(y_pred,y)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

print(loss)
for param in model.parameters():
    print(param)

tensor(1.0880e-14, grad_fn=<MseLossBackward0>)
Parameter containing:
tensor([[ 0.2154, -0.0224, -0.1279,  0.2748,  0.0466, -0.2872, -0.0504, -0.0360,
         -0.2737,  0.2299],
        [-0.2059,  0.2102,  0.1110, -0.2912,  0.1541, -0.2567, -0.1096,  0.0881,
          0.1798,  0.2702],
        [-0.0928, -0.3104, -0.0857, -0.1394,  0.1969, -0.1753, -0.0452,  0.0118,
          0.2740, -0.0769],
        [ 0.0083, -0.1668,  0.2264,  0.2021,  0.0917,  0.0138,  0.0944, -0.0660,
          0.0346, -0.2896],
        [ 0.0664, -0.2323, -0.0289,  0.0187, -0.2996, -0.0556,  0.0011,  0.2688,
         -0.2287,  0.0844],
        [ 0.1495,  0.2473,  0.2686, -0.0926, -0.0498, -0.0444, -0.2043,  0.0120,
          0.0103,  0.0987],
        [-0.0963,  0.1018,  0.1803,  0.0455, -0.0246,  0.3040,  0.0746,  0.2085,
         -0.0750, -0.0915],
        [-0.0130, -0.0524, -0.0156,  0.1751, -0.2751, -0.2322,  0.2204, -0.0968,
          0.0239, -0.2714],
        [-0.0563,  0.1691, -0.1231,  0.2107, -0.0429, -0.30